### ISSUE TITLE
Create a documentation static website for project tracking

### ISSUE THREAD

**Issue by ScottLare** [ScottLare/whitneyhawks#2]
- [X] Make for personal use
- [X] Add one project to start
- [X] Create a company logo
- [X] Create a presentation example
